% % %%
% % %% This is file `book.cls',
% % %% generated with the docstrip utility.

% %% \CharacterTable
% %%  {Upper-case    \A\B\C\D\E\F\G\H\I\J\K\L\M\N\O\P\Q\R\S\T\U\V\W\X\Y\Z
% %%   Lower-case    \a\b\c\d\e\f\g\h\i\j\k\l\m\n\o\p\q\r\s\t\u\v\w\x\y\z
% %%   Digits        \0\1\2\3\4\5\6\7\8\9
% %%   Exclamation   \!     Double quote  \"     Hash (number) \#
% %%   Dollar        \$     Percent       \%     Ampersand     \&
% %%   Acute accent  \'     Left paren    \(     Right paren   \)
% %%   Asterisk      \*     Plus          \+     Comma         \,
% %%   Minus         \-     Point         \.     Solidus       \/
% %%   Colon         \:     Semicolon     \;     Less than     \<
% %%   Equals        \=     Greater than  \>     Question mark \?
% %%   Commercial at \@     Left bracket  \[     Backslash     \\
% %%   Right bracket \]     Circumflex    \^     Underscore    \_
% %%   Grave accent  \`     Left brace    \{     Vertical bar  \|
% %%   Right brace   \}     Tilde         \~}


% \ProvidesClass{thesis}[Custom Thesis Class]
% \LoadClass[12pt]{report}












% % %%%%  ---- Se puede borrar (o no)  ------
% % \newcommand*\chaptermark[1]{}
% % \setcounter{secnumdepth}{2}
% % \newcounter {part}
% % \newcounter {chapter}
% % \newcounter {section}[chapter]
% % \newcounter {subsection}[section]
% % \newcounter {subsubsection}[subsection]
% % \newcounter {paragraph}[subsubsection]
% % \newcounter {subparagraph}[paragraph]
% % \renewcommand \thepart {\@Roman\c@part}
% % \renewcommand \thechapter {\@arabic\c@chapter}
% % \renewcommand \thesection {\thechapter.\@arabic\c@section}
% % \renewcommand\thesubsection   {\thesection.\@arabic\c@subsection}
% % \renewcommand\thesubsubsection{\thesubsection .\@arabic\c@subsubsection}
% % \renewcommand\theparagraph    {\thesubsubsection.\@arabic\c@paragraph}
% % \renewcommand\thesubparagraph {\theparagraph.\@arabic\c@subparagraph}

% % %%%%  ---- Se puede borrar (o no)  ------


% \newcommand\section{\@startsection {section}{1}{\z@}%
%        {-3.5ex \@plus -1ex \@minus -.2ex}%
%        {2.3ex \@plus.2ex}%
%        {\normalfont\Large\bfseries}}
% \newcommand\subsection{\@startsection{subsection}{2}{\z@}%
%      {-3.25ex\@plus -1ex \@minus -.2ex}%
%      {1.5ex \@plus .2ex}%
%      {\normalfont\large\bfseries}}
% \newcommand\subsubsection{\@startsection{subsubsection}{3}{\z@}%
%      {-3.25ex\@plus -1ex \@minus -.2ex}%
%      {1.5ex \@plus .2ex}%
%      {\normalfont\normalsize\bfseries}}
% \newcommand\paragraph{\@startsection{paragraph}{4}{\z@}%
%     {3.25ex \@plus1ex \@minus.2ex}%
%     {-1em}%
%     {\normalfont\normalsize\bfseries}}




% % ======================= ???????
% \newcommand\subparagraph{\@startsection{subparagraph}{5}{\parindent}%
% {3.25ex \@plus1ex \@minus .2ex}%
% {-1em}%
% {\normalfont\normalsize\bfseries}}
% \if@twocolumn
%   \setlength\leftmargini  {2em}
% \else
%   \setlength\leftmargini  {2.5em}
% \fi
% \leftmargin  \leftmargini
% \setlength\leftmarginii  {2.2em}
% \setlength\leftmarginiii {1.87em}
% \setlength\leftmarginiv  {1.7em}
% \if@twocolumn
%   \setlength\leftmarginv  {.5em}
%   \setlength\leftmarginvi {.5em}
% \else
%   \setlength\leftmarginv  {1em}
%   \setlength\leftmarginvi {1em}
% \fi
% \setlength  \labelsep  {.5em}
% \setlength  \labelwidth{\leftmargini}
% \addtolength\labelwidth{-\labelsep}
% \@beginparpenalty -\@lowpenalty
% \@endparpenalty   -\@lowpenalty
% \@itempenalty     -\@lowpenalty
% \renewcommand\theenumi{\@arabic\c@enumi}
% \renewcommand\theenumii{\@alph\c@enumii}
% \renewcommand\theenumiii{\@roman\c@enumiii}
% \renewcommand\theenumiv{\@Alph\c@enumiv}
% % \newcommand\labelenumi{\theenumi.}
% % \newcommand\labelenumii{(\theenumii)}
% % \newcommand\labelenumiii{\theenumiii.}
% % \newcommand\labelenumiv{\theenumiv.}
% \renewcommand\p@enumii{\theenumi}
% \renewcommand\p@enumiii{\theenumi(\theenumii)}
% \renewcommand\p@enumiv{\p@enumiii\theenumiii}
% \newcommand\labelitemi{\textbullet}
% \newcommand\labelitemii{\normalfont\bfseries \textendash}
% \newcommand\labelitemiii{\textasteriskcentered}
% \newcommand\labelitemiv{\textperiodcentered}
% % ======================= ???????

% % ----  MOVER A ARCHIVO .STY ?
% \newenvironment{description}
%                {\list{}{\labelwidth\z@ \itemindent-\leftmargin
%                         \let\makelabel\descriptionlabel}}
%                {\endlist}
% \newcommand*\descriptionlabel[1]{\hspace\labelsep
%                                 \normalfont\bfseries #1}
% \newenvironment{verse}
%                {\let\\\@centercr
%                 \list{}{\itemsep      \z@
%                         \itemindent   -1.5em%
%                         \listparindent\itemindent
%                         \rightmargin  \leftmargin
%                         \advance\leftmargin 1.5em}%
%                 \item\relax}
%                {\endlist}
% \newenvironment{quotation}
%                {\list{}{\listparindent 1.5em%
%                         \itemindent    \listparindent
%                         \rightmargin   \leftmargin
%                         \parsep        \z@ \@plus\p@}%
%                 \item\relax}
%                {\endlist}
% \newenvironment{quote}
%                {\list{}{\rightmargin\leftmargin}%
%                 \item\relax}
%                {\endlist}
% \if@compatibility
% \newenvironment{titlepage}
%     {%
%       \cleardoublepage
%       \if@twocolumn
%         \@restonecoltrue\onecolumn
%       \else
%         \@restonecolfalse\newpage
%       \fi
%       \thispagestyle{empty}%
%       \setcounter{page}\z@
%     }%
%     {\if@restonecol\twocolumn \else \newpage \fi
%     }
% \else
% \newenvironment{titlepage}
%     {%
%       \cleardoublepage
%       \if@twocolumn
%         \@restonecoltrue\onecolumn
%       \else
%         \@restonecolfalse\newpage
%       \fi
%       \thispagestyle{empty}%
%       \setcounter{page}\@ne
%     }%
%     {\if@restonecol\twocolumn \else \newpage \fi
%      \if@twoside\else
%         \setcounter{page}\@ne
%      \fi
%     }
% \fi
% \newcommand\appendix{\par
%   \setcounter{chapter}{0}%
%   \setcounter{section}{0}%
%   \gdef\@chapapp{\appendixname}%
%   \gdef\thechapter{\@Alph\c@chapter}}
% \setlength\arraycolsep{5\p@}
% \setlength\tabcolsep{6\p@}
% \setlength\arrayrulewidth{.4\p@}
% \setlength\doublerulesep{2\p@}
% \setlength\tabbingsep{\labelsep}
% \skip\@mpfootins = \skip\footins
% \setlength\fboxsep{3\p@}
% \setlength\fboxrule{.4\p@}
% \@addtoreset {equation}{chapter}
% \renewcommand\theequation
%   {\ifnum \c@chapter>\z@ \thechapter.\fi \@arabic\c@equation}
% \newcounter{figure}[chapter]
% \renewcommand \thefigure
%      {\ifnum \c@chapter>\z@ \thechapter.\fi \@arabic\c@figure}
% \def\fps@figure{tbp}
% \def\ftype@figure{1}
% \def\ext@figure{lof}
% \def\fnum@figure{\figurename\nobreakspace\thefigure}
% %  ----  MOVER A ARCHIVO .STY ?








% %  ----  MOVER A ARCHIVO .STY ?
% \newenvironment{figure}
%                {\@float{figure}}
%                {\end@float}
% \newenvironment{figure*}
%                {\@dblfloat{figure}}
%                {\end@dblfloat}
% \newcounter{table}[chapter]
% \renewcommand \thetable
%      {\ifnum \c@chapter>\z@ \thechapter.\fi \@arabic\c@table}
% \def\fps@table{tbp}
% \def\ftype@table{2}
% \def\ext@table{lot}
% \def\fnum@table{\tablename\nobreakspace\thetable}
% \newenvironment{table}
%                {\@float{table}}
%                {\end@float}
% \newenvironment{table*}
%                {\@dblfloat{table}}
%                {\end@dblfloat}
% \newlength\abovecaptionskip
% \newlength\belowcaptionskip
% \setlength\abovecaptionskip{10\p@}
% \setlength\belowcaptionskip{0\p@}
% \long\def\@makecaption#1#2{%
%   \vskip\abovecaptionskip
%   \sbox\@tempboxa{#1: #2}%
%   \ifdim \wd\@tempboxa >\hsize
%     #1: #2\par
%   \else
%     \global \@minipagefalse
%     \hb@xt@\hsize{\hfil\box\@tempboxa\hfil}%
%   \fi
%   \vskip\belowcaptionskip}
% \DeclareOldFontCommand{\rm}{\normalfont\rmfamily}{\mathrm}
% \DeclareOldFontCommand{\sf}{\normalfont\sffamily}{\mathsf}
% \DeclareOldFontCommand{\tt}{\normalfont\ttfamily}{\mathtt}
% \DeclareOldFontCommand{\bf}{\normalfont\bfseries}{\mathbf}
% \DeclareOldFontCommand{\it}{\normalfont\itshape}{\mathit}
% \DeclareOldFontCommand{\sl}{\normalfont\slshape}{\@nomath\sl}
% \DeclareOldFontCommand{\sc}{\normalfont\scshape}{\@nomath\sc}
% \DeclareRobustCommand*\cal{\@fontswitch\relax\mathcal}
% \DeclareRobustCommand*\mit{\@fontswitch\relax\mathnormal}
% \newcommand\@pnumwidth{1.55em}
% \newcommand\@tocrmarg{2.55em}
% \newcommand\@dotsep{4.5}
% \setcounter{tocdepth}{2}
% \newcommand\tableofcontents
% {
    
%     \if@twocolumn
%       \@restonecoltrue\onecolumn
%     \else
%       \@restonecolfalse
%     \fi
%     \chapter*{\contentsname
%         \@mkboth{%
%           \MakeUppercase\contentsname}{\MakeUppercase\contentsname}}% 
%           % \hyperlink{toc}{\contentsname}
%     % \chapter*{\hyperlink{toc}{\contentsname}
%     %     \@mkboth{%
%     %       \MakeUppercase\hyperlink{toc}{\contentsname}}{\MakeUppercase\hyperlink{toc}{\contentsname}}}%
% 	\@starttoc{toc}%
%     \if@restonecol\twocolumn\fi
% }
% \newcommand*\l@part[2]{%
%   \ifnum \c@tocdepth >-2\relax
%     \addpenalty{-\@highpenalty}%
%     \addvspace{2.25em \@plus\p@}%
%     \setlength\@tempdima{3em}%
%     \begingroup
%       \parindent \z@ \rightskip \@pnumwidth
%       \parfillskip -\@pnumwidth
%       {\leavevmode
%        \large \bfseries #1\hfil \hb@xt@\@pnumwidth{\hss #2}}\par
%        \nobreak
%          \global\@nobreaktrue
%          \everypar{\global\@nobreakfalse\everypar{}}%
%     \endgroup
%   \fi}
% \newcommand*\l@chapter[2]{%
%   \ifnum \c@tocdepth >\m@ne
%     \addpenalty{-\@highpenalty}%
%     \vskip 1.0em \@plus\p@
%     \setlength\@tempdima{1.5em}%
%     \begingroup
%       \parindent \z@ \rightskip \@pnumwidth
%       \parfillskip -\@pnumwidth
%       \leavevmode \bfseries
%       \advance\leftskip\@tempdima
%       \hskip -\leftskip
%       #1\nobreak\hfil \nobreak\hb@xt@\@pnumwidth{\hss #2}\par
%       \penalty\@highpenalty
%     \endgroup
%   \fi}
% \newcommand*\l@section{\@dottedtocline{1}{1.5em}{2.3em}}
% \newcommand*\l@subsection{\@dottedtocline{2}{3.8em}{3.2em}}
% \newcommand*\l@subsubsection{\@dottedtocline{3}{7.0em}{4.1em}}
% \newcommand*\l@paragraph{\@dottedtocline{4}{10em}{5em}}
% \newcommand*\l@subparagraph{\@dottedtocline{5}{12em}{6em}}
% \newcommand\listoffigures{%
%     \if@twocolumn
%       \@restonecoltrue\onecolumn
%     \else
%       \@restonecolfalse
%     \fi
%     \chapter*{\listfigurename}%
%       \@mkboth{\MakeUppercase\listfigurename}%
%               {\MakeUppercase\listfigurename}%
%     \@starttoc{lof}%
%     \if@restonecol\twocolumn\fi
%     }
% \newcommand*\l@figure{\@dottedtocline{1}{1.5em}{2.3em}}
% \newcommand\listoftables{%
%     \if@twocolumn
%       \@restonecoltrue\onecolumn
%     \else
%       \@restonecolfalse
%     \fi
%     \chapter*{\listtablename}%
%       \@mkboth{%
%           \MakeUppercase\listtablename}%
%          {\MakeUppercase\listtablename}%
%     \@starttoc{lot}%
%     \if@restonecol\twocolumn\fi
%     }
% \let\l@table\l@figure
% \newdimen\bibindent
% \setlength\bibindent{1.5em}
% \newenvironment{thebibliography}[1]
%      {\chapter*{\bibname}%
%       \@mkboth{\MakeUppercase\bibname}{\MakeUppercase\bibname}%
%       \list{\@biblabel{\@arabic\c@enumiv}}%
%            {\settowidth\labelwidth{\@biblabel{#1}}%
%             \leftmargin\labelwidth
%             \advance\leftmargin\labelsep
%             \@openbib@code
%             \usecounter{enumiv}%
%             \let\p@enumiv\@empty
%             \renewcommand\theenumiv{\@arabic\c@enumiv}}%
%       \sloppy
%       \clubpenalty4000
%       \@clubpenalty \clubpenalty
%       \widowpenalty4000%
%       \sfcode`\.\@m}
%      {\def\@noitemerr
%        {\@latex@warning{Empty `thebibliography' environment}}%
%       \endlist}
% \newcommand\newblock{\hskip .11em\@plus.33em\@minus.07em}
% \let\@openbib@code\@empty
% \newenvironment{theindex}
%                {\if@twocolumn
%                   \@restonecolfalse
%                 \else
%                   \@restonecoltrue
%                 \fi 
%                 \twocolumn[\@makeschapterhead{\indexname}]%
%                 \@mkboth{\MakeUppercase\indexname}%
%                         {\MakeUppercase\indexname}%
%                 \thispagestyle{plain}\parindent\z@
%                 \parskip\z@ \@plus .3\p@\relax
%                 \columnseprule \z@
%                 \columnsep 35\p@
%                 \let\item\@idxitem}
%                {\if@restonecol\onecolumn\else\clearpage\fi}
% \newcommand\@idxitem{\par\hangindent 40\p@}
% \newcommand\subitem{\@idxitem \hspace*{20\p@}}
% \newcommand\subsubitem{\@idxitem \hspace*{30\p@}}
% \newcommand\indexspace{\par \vskip 10\p@ \@plus5\p@ \@minus3\p@\relax}
% \renewcommand\footnoterule{%
%   \kern-3\p@
%   \hrule\@width.4\columnwidth
%   \kern2.6\p@}
% \@addtoreset{footnote}{chapter}

% \newcommand\@makefntext[1]{%
%     \parindent 1em%
%     \noindent
%     \hb@xt@1.8em{\hss\@makefnmark}#1}




% \newcommand\contentsname{Contents}
% \newcommand\listfigurename{List of Figures}
% \newcommand\listtablename{List of Tables}
% \newcommand\bibname{Bibliography}
% \newcommand\indexname{Index}
% \newcommand\figurename{Figure}
% \newcommand\tablename{Table}
% \newcommand\partname{Part}
% \newcommand\chaptername{Chapter}
% \newcommand\appendixname{Appendix}
% \def\today{\ifcase\month\or
%   January\or February\or March\or April\or May\or June\or
%   July\or August\or September\or October\or November\or December\fi
%   \space\number\day, \number\year}


% % %  NO TOCAAAARRRRRRRRR  %%%%
% \setlength\columnsep{10\p@}
% \setlength\columnseprule{0\p@}
% \pagestyle{headings}
% \pagenumbering{arabic}


% %  NO TOCAAAARRRRRRRRR  %%%%
% \if@twoside
% \else
%   \raggedbottom
% \fi
% \if@twocolumn
%   \twocolumn
%   \sloppy
%   \flushbottom
% \else
%   \onecolumn
% \fi
% \endinput
% %%
% %% End of file `book.cls'.
